### ISSUE TITLE
Submit the project to ultralisp.org

### ISSUE THREAD

**Issue by ryukinix** [gmasching/sucle#10]
https://ultralisp.org/

I think you'll need to put the `.asd` files in the root of the project to this works, probably.

**Comment by pupcraft** [comment]
Just submitted, although multiple ASDF systems in ```sucle``` need the ```.asd``` files to be in specific locations for relative path resource loading. This would require much rewriting, if the ```.asd``` files were moved to the root of the project. 

> @ryukinix current version of Ultralisp should process asd files in any place.
> 
> However, this produces a problems on some projects like https://github.com/40ants/cl-project-with-docs/blob/master/skeleton/skeleton.asd
> 
> So I decided to make searching asd files only in the root of the project a default policy. And we need to think about a way to specify paths to asd files to be processed by Ultralisp.
A few ASDF systems depend on the ```.asd``` file being in a particular directory. 

 Ultralisp appears to be in beta, so I'll wait [or contribute, ultralisp seems pretty useful] until there are ways to specify paths to ```.asd``` files.

Thanks for letting me know about https://ultralisp.org/ ! It's a nice way to distribute lisp libraries, and could encourage newcomers and old timers alike to share their code more easily in order to promote a better ecosystem. Although I wonder how conflicting namespaces are resolved.

**Comment by ryukinix** [comment]
> Although I wonder how conflicting namespaces are resolved.

That's a problem to be solved. Thanks for submitting!

**Comment by ryukinix** [comment]
It worked! 
![image](https://user-images.githubusercontent.com/7642878/54576034-5c7bf500-49d5-11e9-9f03-f0c830615ad7.png)

**Comment by pupcraft** [comment]
It might be downloading from quicklisp not ultralisp?

```(ql:system-apropos "sucle")``` 

-->

```#<SYSTEM sucle / sucle-20190307-git / quicklisp 2019-03-07>```

 however

```(ql:system-apropos "lisp-chat")``` 

-->
```
#<SYSTEM lisp-chat / lisp-chat-20190307-git / quicklisp 2019-03-07>
#<SYSTEM lisp-chat / ryukinix-lisp-chat-20190317212120 / ultralisp 20190319012501>
```

**Comment by ryukinix** [comment]
> It might be downloading from quicklisp not ultralisp?

It seems true.
